// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6w3soTezq4NlVNg5l9xgQdU3NG_ZVxV8',
    appId: '1:634485010598:web:3f901000cbb42423210467',
    messagingSenderId: '634485010598',
    projectId: 'sweety-1554dd-212app',
    authDomain: 'sweety-1554dd-212app.firebaseapp.com',
    storageBucket: 'sweety-1554dd-212app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNxkGEX24FyoKXPIUeuhWfhFezG2LQmE4',
    appId: '1:634485010598:android:da24c9f6218eafea210467',
    messagingSenderId: '634485010598',
    projectId: 'sweety-1554dd-212app',
    storageBucket: 'sweety-1554dd-212app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO0f_GQPAWs6UaX8bJukES3wtV5DXt3HI',
    appId: '1:634485010598:ios:882014f02d0dc7ce210467',
    messagingSenderId: '634485010598',
    projectId: 'sweety-1554dd-212app',
    storageBucket: 'sweety-1554dd-212app.appspot.com',
    iosClientId: '634485010598-be749qpinbun8mn95atsvtli91risjfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.sweety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO0f_GQPAWs6UaX8bJukES3wtV5DXt3HI',
    appId: '1:634485010598:ios:882014f02d0dc7ce210467',
    messagingSenderId: '634485010598',
    projectId: 'sweety-1554dd-212app',
    storageBucket: 'sweety-1554dd-212app.appspot.com',
    iosClientId: '634485010598-be749qpinbun8mn95atsvtli91risjfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.sweety',
  );
}
